name: Compute minimum supported Rust version for this project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rust-msrv:
    name: Compute minimum supported Rust version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Compute minimum supported Rust version
        uses: spenserblack/actions-msrv@v0.4.1
        id: get-msrv

      - name: Make sure minimum supported Rust version matches that specified in Cargo.toml
        run: |
          MISMATCH=(cargo metadata --no-deps --format-version 1 --all-features --locked | jq '[.packages | .[] | .rust_version | select(. != "${{ steps.get-msrv.outputs.msrv }}")]')
          [[ "$MISMATCH" != "[]" ]] && exit 1
