name: Rust build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rust-build:
    name: Rust build for Rust ${{ matrix.toolchain }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ 1.68.2, stable, beta, nightly ]
        os: [ ubuntu, macos, windows ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain ${{ matrix.toolchain }} with clippy
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: Output Rust toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: |
          cargo check --workspace --all-targets --all-features
          cargo test --workspace --all-features

      - name: Run build
        run: cargo build --all-features --release
