name: Rust build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rust-build:
    name: Rust build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clippy
        run: rustup component add clippy
          
      - name: Output Rust toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: |
          cargo check
          cargo test --all
          
      - name: Run build
        run: cargo build --release
        
      - name: Compute minimum supported Rust version
        uses: spenserblack/actions-msrv@v0.4.1
        id: get-msrv
        
      - name: Output minimum supported Rust version
        run: 'echo "MSRV is ${{ steps.get-msrv.outputs.msrv }}"'
