name: Rust MSRV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rust-msrv:
    name: Compute minimum supported Rust version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Compute minimum supported Rust version
        uses: spenserblack/actions-msrv@v0.4.1
        id: get-msrv

      - name: Output minimum supported Rust version
        run: 'echo "::notice MSRV is ${{ steps.get-msrv.outputs.msrv }}"'

      - name: Make sure minimum supported Rust version matches that specified in Cargo.toml
        run: |
          CARGO_METADATA=$(cargo metadata --no-deps --format-version 1 --all-features --locked)
          MISMATCH=$(jq '[.packages | .[] | .rust_version | select(. != "${{ steps.get-msrv.outputs.msrv }}")]' <<< "$CARGO_METADATA")
          if [[ "$MISMATCH" != "[]" ]]
            echo "::error MSRV is ${{ steps.get-msrv.outputs.msrv }}, but found some mismatch in Cargo.toml: $MISMATCH"
          fi
